version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 10
    groups:
      patches:
        patterns:
          - '*'
        update-types:
          - 'patch'
      minors:
        patterns:
          - '*'
        update-types:
          - 'minor'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'major'
    labels:
      - 'dependencies'
    reviewers:
      - 'malon-team'
